services:
  xray-argo:
    image: novre/xray-argo:v1.0-26826
    container_name: xray-argo
    restart: always
    environment:
      - UUID=
      - DOMAIN=
      - ARGO_TOKEN=
      - VMESS_PORT=
      - WS_PATH=
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
